version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - errname
    - errorlint
    - govet
    - ineffassign
    - nilnil
    - perfsprint
    - prealloc
    - reassign
    - staticcheck
    - unused

formatters:
  enable:
    - gci
    - gofumpt
    - golines

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
